### ISSUE TITLE
NameError: global name 'count_lock' is not defined

### ISSUE THREAD

**Issue by xoyabc** [Wildog/douban-exporter#8]
The detailed error message is as follows.
```
C:\Users\username\Downloads\douban-exporter-master>python exporter.py
Process Process-2:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xiaohui.lou\Downloads\douban-exporter-master\exporter.py", line
 363, in export
    with count_lock:
NameError: global name 'count_lock' is not defined
```
Hope you can give me some help if it is convenient to you.

**Comment by Wildog** [comment]
As said in README, this project doesn't work on Windows currently.

**Comment by xoyabc** [comment]
@Wildog  I'm sorry to disturb you so much.

**Comment by xoyabc** [comment]
@Wildog  Can you tell me why it is not available on Windows? Component support or any other reason?

**Comment by Wildog** [comment]
@xoyabc It's the problem of multiprocessing behaves differently on Unix and Windows. multiprocessing uses fork() to spawn new processes on Unix but not on Windows. Necessary changes must be made to share memory between processes on Windows. 
I don't work on Windows and I don't have the time to develop and test on Windows. Also this project is somewhat on halt, due to Douban's more restrict policy on anti crawler. Introducing proxy pool to this project might be the sole solution. But I'm currently busy and might not be able to spare my time on this project.

**Comment by xoyabc** [comment]
@Wildog Thanks for your detailed explanation.
